xserver-nodm-init-2.0: Remove recipe
The version in oe-core should now do everything this one does with one
exception: it does not RDEPEND on xserver-common. This dependency now
needs to be set explicitly.

Signed-off-by: Jussi Kukkonen <jussi.kukkonen@intel.com>